### ISSUE TITLE
Call to a member function getValue() on  null

### ISSUE THREAD

**Issue by davoc** [enrico69/magento2-customer-activation#15] opened 2018-03-05 14:22 UTC
I have installed your module, cleared caches, reindexed, run setup:upgrade and wherever I call:

$customer->getCustomAttribute(InstallData::CUSTOMER_ACCOUNT_ACTIVE)->getValue() !== '1'

I am getting the error 

( ! )  Fatal error: Uncaught Error: Call to a member function getValue() on  null 

I have had the module working but when migrating from development to live I get this error on the live server. I think it is some kind of discrepancy in the database. I'm using Magento v2.1.7 and v1.4 of your module. Any way I can fix this error please?

**Comment by enrico69** [comment] 2018-03-05 14:29
HIi @davoc 
As you can see it on the repository main page, the 1.4 is buggy.
The 1.3.2 is the last stable version.

However I am surprised as it is the first time I see this error.
If the problem persist, let me know.

**Comment by davoc** [comment] 2018-03-05 14:40
It seems as though no attributes have been set up in the database. When I print_r($customer->getCustomAttributes()) I get an empty array.
I'll try completely uninstalling the module and reinstalling again with 1.3.2 and update

**Comment by davoc** [comment] 2018-03-05 16:07
I've uninstalled 1.4 and installed 1.3.2 but this issue is still persisting

**Comment by enrico69** [comment] 2018-03-06 01:24
Thats' very weird because the attributes should be here with a default value of 1.
We use this version on production without any issue.

Could you see the attribute in the corresponding EAV table? Could you edit a customer in the back-office and save the value? Do you use other third-party modules?

As a temporary but effective fix, create an override of the faulty class. In the override do the following:
- check the existence of the attribute
- id it doesn't exist, force it to 1.
- Test many different use cases to be sure that the fix works.

**Comment by nafisa-kazma** [comment] 2018-03-27 08:06
How to resolved issue? please help me asap.
Fatal error: Uncaught Error: Call to a member function getValue() on null in /home/trophykart/public_html/vendor/enrico69/magento2-customer-activation/Plugin/Confirm.php:110 Stack trace: #0 /home/trophykart/public_html/lib/internal/Magento/Framework/Interception/Interceptor.php(152): Enrico69\Magento2CustomerActivation\Plugin\Confirm->afterExecute(Object(Magento\Customer\Controller\Account\Confirm\Interceptor), Object(Magento\Framework\Controller\Result\Redirect\Interceptor)) #1 /home/trophykart/public_html/var/generation/Magento/Customer/Controller/Account/Confirm/Interceptor.php(26): Magento\Customer\Controller\Account\Confirm\Interceptor->___callPlugins('execute', Array, Array) #2 /home/trophykart/public_html/lib/internal/Magento/Framework/App/Action/Action.php(102): Magento\Customer\Controller\Account\Confirm\Interceptor->execute() #3 /home/trophykart/public_html/lib/internal/Magento/Framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http)) #4 in /home/trophykart/public_html/vendor/enrico69/magento2-customer-activation/Plugin/Confirm.php on line 110

**Comment by enrico69** [comment] 2018-03-27 22:32
OK I am going to test this this week and make a fix if needed.

**Comment by enrico69** [comment] 2018-04-20 01:49
Hey folks.

We managed to reproduce the code. It occurs on Magento 2.2.x (again, this update has a lot of side effects) on customer which registered BEFORE the activation of the module. So we are going to fix it in the 1.4.2, to be released in the next days.

**Comment by enrico69** [comment] 2018-05-01 00:30
Fixed in 1.4.2

**Comment by nafisa-kazma** [comment] 2018-05-02 12:46
Thank you

**Closed as completed** 2018-05-31 12:31 UTC
Labels: bug, Fixed / Completed
